# Last Horizon - i3 Colors
set $bg        #0c0b0c
set $bg-alt    #0c0b0c
set $fg        #FAFCFB
set $primary   #b59790
set $secondary #a5a0b6
set $alert     #c38b7b
set $disabled  #584e51
set $green     #87a9b0
set $pink      #c4d8e2
set $yellow    #6B5E73

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
