# Catppuccin Mocha - i3 Colors
set $bg        #1e1e2e
set $bg-alt    #313244
set $fg        #cdd6f4
set $primary   #89b4fa
set $secondary #89dceb
set $alert     #f38ba8
set $disabled  #6c7086
set $green     #a6e3a1
set $pink      #f5c2e7
set $yellow    #f9e2af

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
