# Rosé Pine - i3 Colors
set $bg        #232136
set $bg-alt    #5a5868
set $fg        #e0def4
set $primary   #56949f
set $secondary #d7827e
set $alert     #b4637a
set $disabled  #6e6a86
set $green     #286983
set $pink      #907aa9
set $yellow    #ea9d34

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
