# Tokyo Night - i3 Colors
set $bg        #0B0C16
set $bg-alt    #3E4058
set $fg        #ddf7ff
set $primary   #82FB9C
set $secondary #7cf8f7
set $alert     #50f872
set $disabled  #3E4058
set $green     #4fe88f
set $pink      #86a7df
set $yellow    #50f7d4

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
