# Kanagawa - i3 Colors
set $bg        #1f1f28
set $bg-alt    #57575d
set $fg        #dcd7ba
set $primary   #7e9cd8
set $secondary #6a9589
set $alert     #c34043
set $disabled  #54546d
set $green     #76946a
set $pink      #957fb8
set $yellow    #c0a36e

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
