# Miasma - i3 Colors
set $bg        #222222
set $bg-alt    #000000
set $fg        #c2c2b0
set $primary   #78824b
set $secondary #c9a554
set $alert     #685742
set $disabled  #000000
set $green     #5f875f
set $pink      #bb7744
set $yellow    #b36d43

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
