[colors.primary]
background = "#0c0b0c"
foreground = "#FAFCFB"

[colors.normal]
black   = "#0c0b0c"
red     = "#c38b7b"
green   = "#87a9b0"
yellow  = "#6B5E73"
blue    = "#b59790"
magenta = "#c4d8e2"
cyan    = "#a5a0b6"
white   = "#cfd3cd"

[colors.bright]
black   = "#584e51"
red     = "#c38b7b"
green   = "#87a9b0"
yellow  = "#6B5E73"
blue    = "#b59790"
magenta = "#c4d8e2"
cyan    = "#a5a0b6"
white   = "#e2dddc"
