# Dracula - i3 Colors
set $bg        #282a36
set $bg-alt    #3c3e4a
set $fg        #f8f8f2
set $primary   #bd93f9
set $secondary #8be9fd
set $alert     #ff5555
set $disabled  #6272a4
set $green     #50fa7b
set $pink      #ff79c6
set $yellow    #f1fa8c

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
