# Ristretto - i3 Colors
set $bg        #2c2525
set $bg-alt    #605b5b
set $fg        #e6d9db
set $primary   #f38d70
set $secondary #85dacc
set $alert     #fd6883
set $disabled  #72696a
set $green     #adda78
set $pink      #a8a9eb
set $yellow    #f9cc6c

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
