# Catppuccin Latte - i3 Colors
set $bg        #1e1e2e
set $bg-alt    #565662
set $fg        #cdd6f4
set $primary   #1e66f5
set $secondary #179299
set $alert     #d20f39
set $disabled  #5c5f77
set $green     #40a02b
set $pink      #ea76cb
set $yellow    #df8e1d

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
