# Flexoki Light - i3 Colors
set $bg        #1c1c1c
set $bg-alt    #545454
set $fg        #dad8ce
set $primary   #205EA6
set $secondary #3AA99F
set $alert     #D14D41
set $disabled  #878580
set $green     #879A39
set $pink      #CE5D97
set $yellow    #D0A215

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
