[colors.primary]
background = "#060B1E"
foreground = "#ffcead"

[colors.normal]
black   = "#3C486D"
red     = "#ED5B5A"
green   = "#92a593"
yellow  = "#E9BB4F"
blue    = "#7d82d9"
magenta = "#c89dc1"
cyan    = "#a3bfd1"
white   = "#F99957"

[colors.bright]
black   = "#6d7db6"
red     = "#ED5B5A"
green   = "#92a593"
yellow  = "#E9BB4F"
blue    = "#7d82d9"
magenta = "#c89dc1"
cyan    = "#a3bfd1"
white   = "#ffcead"
