[colors.primary]
background = "#101315"
foreground = "#cacccc"

[colors.normal]
black   = "#181c22"
red     = "#8a6068"
green   = "#688a70"
yellow  = "#8a8268"
blue    = "#68708a"
magenta = "#7a688a"
cyan    = "#688a8a"
white   = "#cbc2be"

[colors.bright]
black   = "#2a3038"
red     = "#a87078"
green   = "#78a880"
yellow  = "#a89878"
blue    = "#7880a8"
magenta = "#8878a8"
cyan    = "#78a8a8"
white   = "#d8d4d0"
