# Everforest - i3 Colors
set $bg        #2d353b
set $bg-alt    #61676c
set $fg        #d3c6aa
set $primary   #7fbbb3
set $secondary #83c092
set $alert     #e67e80
set $disabled  #475258
set $green     #a7c080
set $pink      #d699b6
set $yellow    #dbbc7f

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
