# Nord - i3 Colors
set $bg        #2e3440
set $bg-alt    #3b4252
set $fg        #d8dee9
set $primary   #81a1c1
set $secondary #81a1c1
set $alert     #bf616a
set $disabled  #4c566a
set $green     #a3be8c
set $pink      #b48ead
set $yellow    #ebcb8b

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
