[colors.primary]
background = "#16242d"
foreground = "#d6e2ee"

[colors.normal]
black   = "#1b2d40"
red     = "#4d86b0"
green   = "#5e95bc"
yellow  = "#6fa4c9"
blue    = "#6fb8e3"
magenta = "#8bc9eb"
cyan    = "#b4e4f6"
white   = "#d6e2ee"

[colors.bright]
black   = "#304860"
red     = "#4d86b0"
green   = "#5e95bc"
yellow  = "#6fa4c9"
blue    = "#6fb8e3"
magenta = "#8bc9eb"
cyan    = "#b4e4f6"
white   = "#ffffff"
