[colors.primary]
background = "#2c2525"
foreground = "#e6d9db"

[colors.normal]
black   = "#2f3347"
red     = "#fd6883"
green   = "#adda78"
yellow  = "#f9cc6c"
blue    = "#f38d70"
magenta = "#a8a9eb"
cyan    = "#73daca"
white   = "#c0caf5"

[colors.bright]
black   = "#565f89"
red     = "#fd6883"
green   = "#adda78"
yellow  = "#f9cc6c"
blue    = "#f38d70"
magenta = "#a8a9eb"
cyan    = "#73daca"
white   = "#ffffff"
