# ─── Aplicaciones Predeterminadas ───
# Editado por el menú de Configuración → Aplicaciones
# No editar manualmente mientras el menú esté abierto

TERMINAL="alacritty"
BROWSER="firefox"
FILE_MANAGER="nemo"
TERMINAL_FILE_MANAGER="ranger"
