# Lumon - i3 Colors
set $bg        #16242d
set $bg-alt    #1b2d40
set $fg        #d6e2ee
set $primary   #8bc9eb
set $secondary #b4e4f6
set $alert     #4d86b0
set $disabled  #304860
set $green     #5e95bc
set $pink      #8bc9eb
set $yellow    #6fa4c9

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
