# Vantablack - i3 Colors
set $bg        #000000
set $bg-alt    #404040
set $fg        #ffffff
set $primary   #8d8d8d
set $secondary #b0b0b0
set $alert     #a4a4a4
set $disabled  #404040
set $green     #b6b6b6
set $pink      #9b9b9b
set $yellow    #cecece

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
