backend = "glx";
vsync = true;

corner-radius = 12;
round-borders = 1;
detect-rounded-corners = true;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.4;

blur-method = "dual_kawase";
blur-strength = 5;

@include "../../../animations/global.picom"


@include "../../../animations/rules.picom"

