# Tokyo Night - i3 Colors
set $bg        #060B1E
set $bg-alt    #3C486D
set $fg        #ffcead
set $primary   #7d82d9
set $secondary #a3bfd1
set $alert     #ED5B5A
set $disabled  #3C486D
set $green     #92a593
set $pink      #c89dc1
set $yellow    #E9BB4F

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
