# Tokyo Night - i3 Colors
set $bg        #1a1a24
set $bg-alt    #c0c0c0
set $fg        #c0c0c0
set $primary   #6e6e6e
set $secondary #3e3e3e
set $alert     #2a2a2a
set $disabled  #5c5c5c
set $green     #3a3a3a
set $pink      #2e2e2e
set $yellow    #4a4a4a

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
