# White - i3 Colors
set $bg        #1a1a24
set $bg-alt    #323248
set $fg        #cdd6e8
set $primary   #6c9be8
set $secondary #7ac4c4
set $alert     #f07178
set $disabled  #3a3a4e
set $green     #7bc275
set $pink      #c08ae6
set $yellow    #e6c384

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
