# Matte Black - i3 Colors
set $bg        #121212
set $bg-alt    #4d4d4d
set $fg        #bebebe
set $primary   #e68e0d
set $secondary #bebebe
set $alert     #D35F5F
set $disabled  #333333
set $green     #FFC107
set $pink      #D35F5F
set $yellow    #FFC107

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
