# Osaka Jade - i3 Colors
set $bg        #111c18
set $bg-alt    #4c5451
set $fg        #C1C497
set $primary   #509475
set $secondary #2DD5B7
set $alert     #FF5345
set $disabled  #53685B
set $green     #549e6a
set $pink      #D2689C
set $yellow    #459451

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
