# Tokyo Night - i3 Colors
set $bg        #101315
set $bg-alt    #101315
set $fg        #cacccc
set $primary   #798186
set $secondary #aeaeae
set $alert     #565d60
set $disabled  #4b4e55
set $green     #9fa5a9
set $pink      #aeaeae
set $yellow    #d9dbdc

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
