# Gruvbox - i3 Colors
set $bg        #282828
set $bg-alt    #3c3836
set $fg        #ebdbb2
set $primary   #d79921
set $secondary #98971a
set $alert     #cc241d
set $disabled  #7c6f64
set $green     #b8bb26
set $pink      #d3869b
set $yellow    #fabd2f

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
