# Retro 82 - i3 Colors
set $bg        #05182e
set $bg-alt    #303442
set $fg        #f6dcac
set $primary   #faa968
set $secondary #8cbfb8
set $alert     #f85525
set $disabled  #303442
set $green     #028391
set $pink      #3f8f8a
set $yellow    #e97b3c

client.focused          $primary $primary $fg $primary $pink
client.focused_inactive $disabled $bg-alt $fg $bg-alt $bg-alt
client.unfocused        $bg-alt $bg-alt $fg $bg-alt $bg-alt
client.urgent           $alert $alert $fg $alert $alert
client.background       $bg
